<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>TCPIPBase Library</Title>
    <Description>Small and simple TCP/IP library</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logging\Logging.csproj" />
    <ProjectReference Include="..\SecsGemHelperClasses\SecsGemHelperClasses.csproj" />
  </ItemGroup>

</Project>
