<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>TCPIPBase Library</Title>
    <Description>Small and simple TCP/IP library</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logging\Logging.csproj" />
    <ProjectReference Include="..\SecsGemHelperClasses\SecsGemHelperClasses.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400" />
    <PackageReference Update="Nerdbank.GitVersioning" Version="3.10.94" />
  </ItemGroup>

</Project>
