<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>SECS/GEM Message Handler</Title>
    <Description>Small library class to send and receive SECS/GEM messages</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logging\Logging.csproj" />
    <ProjectReference Include="..\SecsGemBaseItems\SecsGemBaseItems.csproj" />
    <ProjectReference Include="..\SecsGemHelperClasses\SecsGemHelperClasses.csproj" />
    <ProjectReference Include="..\TCPIPBaseLibrary\TCPIPBaseLibrary.csproj" />
  </ItemGroup>

</Project>
