<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Logging</Title>
    <Description>Defines interfaces for logging of SECS/GEM messages</Description>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecsGemBaseItems\SecsGemBaseItems.csproj" />
  </ItemGroup>

</Project>
